name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy src directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src  # The directory you want to publish
